# Generated by Django 2.2.3 on 2019-07-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email Address')),
                ('interests', models.CharField(max_length=15, verbose_name='Interests')),
                ('program', models.CharField(max_length=20, verbose_name='Program')),
                ('year', models.IntegerField(max_length=2, verbose_name='Year')),
            ],
        ),
    ]
