# Generated by Django 2.2.3 on 2019-07-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('program', models.CharField(max_length=20, verbose_name='Program')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=10, verbose_name='Team Name')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit_app.Form_Response')),
            ],
        ),
    ]
