# Generated by Django 2.2.3 on 2019-07-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_response',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
