# Generated by Django 2.2.3 on 2019-07-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0002_auto_20190718_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='recruit',
        ),
        migrations.AddField(
            model_name='form_response',
            name='interests',
            field=models.ManyToManyField(to='recruit_app.Team'),
        ),
    ]
