# Generated by Django 2.2.3 on 2019-07-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0003_auto_20190718_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_response',
            name='interests',
            field=models.ManyToManyField(blank=True, to='recruit_app.Team'),
        ),
    ]
